language: csharp
jobs:
  include:
    - os: linux
      dotnet: 3.0.100
      mono: none
      env: DOTNETCORE=3
    - os: linux
      mdotnet: 2.2.402
      mono: none
    - os: osx
      osx_image: xcode11
      dotnet: 3.0.100
      mono: none
      env: DOTNETCORE=3
    - os: osx
      osx_image: xcode11
      dotnet: 2.2.402
      mono: none
sudo: false  # use the new container-based Travis infrastructure
script:
  - if [ "$DOTNETCORE" = "3" ]; then 
      dotnet restore ./src/Vlingo.UUID.sln;
      dotnet build ./src/Vlingo.UUID.sln;
      dotnet test ./src/Vlingo.UUID.Tests/Vlingo.UUID.Tests.csproj;
    else
      dotnet restore ./src/Vlingo.UUID.sln;
      dotnet build ./src/Vlingo.UUID.sln;
      dotnet test ./src/Vlingo.UUID.Tests/Vlingo.UUID.Tests.csproj;
    fi

notifications:
  slack: vlingo-platform-net:kwiEEBuUpRnz2rYYYstTBpXr