language: csharp
jobs:
  include:
    - os: linux
      dotnet: 3.0.100
      mono: none
      env: DOTNETCORE=3
    - os: linux
      mono: latest
      env: MONO=latest
    - os: osx
      osx_image: xcode11
      dotnet: 3.0.100
      mono: none
      env: DOTNETCORE=3
    - os: osx
      osx_image: xcode11
      mono: latest
      env: MONO=latest
sudo: false  # use the new container-based Travis infrastructure
install:
  - if [ "$MONO" = "latest" ]; then 
      nuget src/Vlingo.UUID.sln;
      nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner;
    fi
script:
  - if [ "$DOTNETCORE" = "3" ]; then 
      dotnet restore ./src/Vlingo.UUID.sln;
      dotnet build ./src/Vlingo.UUID.sln;
      dotnet test ./src/Vlingo.UUID.Tests/Vlingo.UUID.Tests.csproj;
    else
      cd src
      msbuild Vlingo.UUID.sln /p:Configuration=Release
      mono ../testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Vlingo.UUID.Tests/bin/Release/net40/Vlingo.UUID.Tests.dll;
      mono ../testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Vlingo.UUID.Tests/bin/Release/net45/Vlingo.UUID.Tests.dll;
      mono ../testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Vlingo.UUID.Tests/bin/Release/netstandard2.1/Vlingo.UUID.Tests.dll;
    fi

notifications:
  slack: vlingo-platform-net:kwiEEBuUpRnz2rYYYstTBpXr